In [ ]:
Introduction to Statistical functions in numpy:

In [3]:
import numpy as np

In [4]:
test_scores = np.array([32.33,27.8,56.98,44.32,0.65,43.44])

In [5]:
print("Mean test score of the students:")
print(np.mean(test_scores))

Mean test score of the students:
34.25333333333333


In [6]:
print("Median test score of the students:")
print(np.median(test_scores))

Median test score of the students:
37.885


In [9]:
salaries = np.genfromtxt('salary.csv',delimiter=',')
print(salaries)

[60000. 58000. 56967. ... 54647. 25000. 70000.]


In [ ]:
req: mean, median,variance,standarddeviation.

In [10]:
print(np.mean(salaries))

55894.53879686138


In [11]:
m = np.mean(salaries)
md = np.median(salaries)
v = np.var(salaries)
sd = np.std(salaries)

In [15]:
print('Mean = %i' %m)  ### Older approach to reference variables
print('Meian = %i' %md)
print('Variance = %i' %v)
print('Standarddeviation = %i' %sd)

Mean = 55894
Meian = 48000
Variance = 3043770333
Standarddeviation = 55170


In [21]:
print(f"Mean = {m:.1f}\nMedian = {md:.1f}\nVariance = {v:.1f}\nStandardDeviation = {sd}")

Mean = 55894.5
Median = 48000.0
Variance = 3043770333.8
StandardDeviation = 55170.37550939316


In [ ]:
Introduction to iteration in numpy:

In [16]:
a = np.arange(11)**2

In [17]:
a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [22]:
a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [23]:
a**(1/2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
d = a**(2)

In [25]:
d


array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000], dtype=int32)