In [ ]:
Getting started with Numpy :

In [ ]:
Understanding Numpy :
    It is used to do the numerical computations.  It also forms a foundational layer for the 
    scientific computations as well.

In [ ]:
Datatype of Numpy : Arrays.====> Numpy array much similar to a list....

In [1]:
import numpy as np  ##np....is alias name 

In [2]:
array_one = np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [3]:
type(array_one) ##nd ----> ndimensions...


numpy.ndarray

In [ ]:
## Variable names should be logical.

In [4]:
numbers = [9,8,7,6]
array_two = np.array(numbers) ## Passing variable
array_two

array([9, 8, 7, 6])

In [5]:
array_of_zeros = np.zeros((3,4)) ##x,y (x --- rows, y--- colums)
array_of_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
## Internally numpy would be working on float datatype --- decimals 0.8,0.9

In [6]:
array_of_ones = np.ones((4,5)) ## 4 by 5 matrix  
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)  ##int16, int32,int64..

In [8]:
array_of_ones_int


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)