In [1]:
import numpy as np

In [ ]:
identity matrix:

In [2]:
array_eye = np.eye(4)  ##Identity matrix (diagonal 1)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
array_eye1 = np.eye(3)
array_eye1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Req: 1 to 20 numbers 

In [7]:
array_of_numbers = np.arange(1,20)
array_of_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
array_of_evens = np.arange(2,31,2) ## Last value is always exclusive
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
##Req.  create a simple array with 6 numbers

In [11]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [13]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
(x)----Single dimension  (x,y)---Two dimension (x,y,z)--- 3 dimension

In [14]:
x.shape ## One dimension

(6,)

In [15]:
y = np.arange(6).reshape(2,3) ## 2x3 = 6
y

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
y.shape  ## 2 dimension

(2, 3)

In [18]:
z = np.arange(12).reshape(2,3,2) ## 2x3x2=12
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [19]:
z.shape

(2, 3, 2)

In [21]:
z = np.arange(12).reshape(2,6) ## 2x6=12
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])